services:
  postgres:
    image: postgres:17

    container_name: shoppilot-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: shoppilot
      POSTGRES_PASSWORD: shoppilot
      POSTGRES_DB: shoppilot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: