import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

type QuotePdfData = {
  quoteNumber: string;
  status: string;
  createdAt: Date;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  customer: {
    name: string;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  tenant: {
    name: string;
    businessType: string;
  };
  items: {
    productName: string;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
  }[];
};

@Injectable()
export class PdfService {
  generateQuotePdf(quote: QuotePdfData): PDFKit.PDFDocument {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
    });

    doc.fontSize(22).text(quote.tenant.name, { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(14).text('Quotation', { align: 'center' });

    doc.moveDown(2);

    doc.fontSize(10);
    doc.text(`Quote No: ${quote.quoteNumber}`);
    doc.text(`Status: ${quote.status}`);
    doc.text(`Date: ${new Date(quote.createdAt).toLocaleDateString('en-IN')}`);

    doc.moveDown();

    doc.fontSize(12).text('Customer', { underline: true });
    doc.fontSize(10);
    doc.text(quote.customer.name);
    if (quote.customer.phone) doc.text(`Phone: ${quote.customer.phone}`);
    if (quote.customer.email) doc.text(`Email: ${quote.customer.email}`);
    if (quote.customer.address) doc.text(`Address: ${quote.customer.address}`);

    doc.moveDown(1.5);

    const startX = 50;
    let y = doc.y;

    doc.fontSize(11).text('Product', startX, y);
    doc.text('Qty', 300, y, { width: 50, align: 'right' });
    doc.text('Unit Price', 360, y, { width: 80, align: 'right' });
    doc.text('Total', 460, y, { width: 80, align: 'right' });

    y += 20;
    doc.moveTo(startX, y).lineTo(545, y).stroke();

    y += 10;

    quote.items.forEach((item) => {
      doc.fontSize(10).text(item.productName, startX, y, { width: 230 });
      doc.text(String(item.quantity), 300, y, { width: 50, align: 'right' });
      doc.text(String(item.unitPrice), 360, y, { width: 80, align: 'right' });
      doc.text(String(item.lineTotal), 460, y, { width: 80, align: 'right' });

      y += 24;
    });

    y += 10;
    doc.moveTo(startX, y).lineTo(545, y).stroke();

    y += 20;

    doc.fontSize(11);
    doc.text(`Subtotal: ₹${quote.subtotal}`, 360, y, {
      width: 180,
      align: 'right',
    });
    y += 20;
    doc.text(`Tax: ₹${quote.taxAmount}`, 360, y, {
      width: 180,
      align: 'right',
    });
    y += 20;
    doc.fontSize(14).text(`Total: ₹${quote.totalAmount}`, 360, y, {
      width: 180,
      align: 'right',
    });

    doc.moveDown(4);
    doc.fontSize(9).text('Generated by ShopPilot', { align: 'center' });

    doc.end();

    return doc;
  }
}
