services:
  - type: web
    name: api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
